#
# Application Deployment action
#
# This is used muliple times in the release pipeline
# to ensure consistent deployments in different environments
#

name: 'CISync Build'
description: 'Builds the web site and functions for CI Sync'

inputs:
  # sample inputs. Tokens and credentials will need to be
  # passed in by caller.
  token:
    description: 'Secret Deployment Token'
    required: true
  config:
    description: 'Secret Config'
    requred: true

runs:

  using: 'composite'
  steps:
    - name: Load Artifacts
      run: echo Loading Artifacts...
      shell: bash

    - name: Deploy
      env:
        # the actual values will be redacted if they are secrets
        DUMP_INPUTS: ${{ toJson(inputs) }}
      run: |
        echo Deploying to ${{ inputs.environment }}...
        echo "$DUMP_INPUTS"
      shell: bash



