# This is a basic workflow to help you get started with Actions

name: Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Functions
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Publish Artefacts
        run: echo Publishing Artefacts...

  test:
    name: Test Functions
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - name: Load Artefacts
        run: echo Loading Artefacts...

      - name: Run Tests
        run: echo Running Tests...

  deploy:
    strategy:
      matrix:
        environment: ['dev', 'test', 'prd-customer1', 'prd-customer2']
    name: Deploy to ${{ matrix.environment }} Environment
    runs-on: ubuntu-latest
    needs: ['test']
    steps:
      - name: Deploy Functions
        run: echo Deploying functions to ${{ matrix.environment }}...

      - name: Deploy Web Site
        run: echo Deploying web site to ${{ matrix.environment }}...

