#
# The Pull Request Workflow
#
# This workflow executes on a pull request to main branch.
# It performs a build and test cycle to ensure minimum quality
# requirement and tests pass.
#
# We could choose to enable this for any branch or specific patterns
# like 'release/*'
#

name: PR Build and Test

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  # Do a build of the application, and publish the artifacts
  build:
    name: Build Functions
    runs-on: ubuntu-latest

    steps:
      # NOTE: we must checkout first becasue we need access to
      #       the build actions in the repository
      #
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Use the common build action that is also used for PRs in a
      # different workflow
      - uses: ./.github/actions/build


